### ISSUE TITLE
need some demo

### ISSUE THREAD

**Issue by geminiyellow** [alienfast/i18next-loader#10]
follow the README, but could not working. 
could you give an example ?

@alienfast-build

**Comment by rosskevin** [comment]
The readme describes every file in an example. The test directory has locales that are used for testing; you may look at those as well. Aside from that and absent a reproduction of your problem, I'm not sure I can help.

Perhaps you should put together a sample repository with your setup and then I can take a look.

**Comment by anardil** [comment]
Hello,

Me too, a full example will be nice.
I try to work with VueJs and it's not working.
A repository with a full example with VueJs will be nice.

**Comment by rosskevin** [comment]
> Perhaps you should put together a sample repository with your setup and then I can take a look.

**Comment by geminiyellow** [comment]
oh, @rosskevin , i tried, but failed, 
so i gave up use this loader and i18next,
and everything working well,  
because of that i forgot close this issue,
don't worry, i just want to say thank you, not reopen.
thank you again.
