### ISSUE TITLE
Typescript: /src/locales/index.ts' is not a module.  TS2306

### ISSUE THREAD

**Issue by adorum** [alienfast/i18next-loader#14]
I aligned the directory structure based on docs, but gettng error `/src/locales/index.ts' is not a module.  TS2306`. I am import the locales dir in a folllowing way: `import * as resources from "./locales";`. Index.ts is empty as docs suggests.

**Comment by rosskevin** [comment]
This is going to be dependent on your tooling setup.

Try adding an empty index.js next to your index.ts.

**Comment by adorum** [comment]
I am running on default `yarn create react-app my-app --typescript` project structure. Just added i18n related stuff. Adding `index.js` next to ts didnt help.

**Comment by rosskevin** [comment]
I'm going to close this out for housekeeping.  Configuring webpack properly (CRA or otherwise) is not really something this project has responsibility.  If you do find a solution please comment in case others bump into the same.
