### ISSUE TITLE
mocha fails to import json when using import syntax

### ISSUE THREAD

**Issue by buggedcom** [alienfast/i18next-loader#15]
Hi,

I'm building an app using `CRA` and `react-app-rewired` and I'm using the import syntax to import the combined json files like so.

```js
import resources from '@alienfast/i18next-loader!app/i18n/locales/index?{relativePathAsNamespace:true}';
```

This works fine when building the app, however when running the tests through mocha the import syntax fails and I have struggled for a while to approach getting it working.

```
Error: Cannot find module '@alienfast/i18next-loader!app/i18n/locales/index?{relativePathAsNamespace:true}'
```

I can't eject CRA for various reasons and am at a loose end. Do you know of an easy way to get this working?

**Comment by rosskevin** [comment]
Sorry, I don't....

BUT

My guess is that it is a path issue with mocha.  You may need to initialize/setup mocha and point to the proper root dir vs cwd so that the path is correct. Check out material-ui, I believe they still use mocha and do some similar app module path setup.

Also, turn on debug for this loader, it might yield some information that is useful.

**Comment by buggedcom** [comment]
Thanks.

For anyone else reading this, I switched over to jest for testing and then added the following to `moduleNameMapper` in the jest.config.js file for the tests.

```
    // A map from regular expressions to module names that allow to stub out resources with a single module
    moduleNameMapper : {
//        ...
        "@alienfast/i18next-loader!.*" : "<rootDir>../i18n.loader.js"
//        ...
    },
```

Where the `i18n.loader.js` script is

```js
const alienfastLoader = require('@alienfast/i18next-loader');

const query = '?{relativePathAsNamespace:true}';
const resource = 'src/app/i18n/locales/index.js';

eval(
    alienfastLoader.call({
        query,
        resource,
        addContextDependency : () => {
        },
        addDependency : () => {
        },
    })
);
```
