### ISSUE TITLE
TypeScript import error 

### ISSUE THREAD

**Issue by wapcrazut** [alienfast/i18next-loader#17]
I'm working on a project that needs to load translations from `.json` files, so I followed the instructions and it fails while trying to import the resources as in the example:

I have a main file for the project called `index.ts`

I added:

```
import i18n from "i18next";
import * as resources from "../assets/i18n";

i18n.init({
    resources
});
```

The project's folders are organized like this:

```
├── assets
│   └── i18n
│       ├── en
│       │   └── translation.json
│       └── index.js
└── ts
    ├── ...
    └── index.ts

```

But I get an error when trying to compile the files:

```
ERROR in /home/me/project/src/ts/index.ts
    ./src/ts/index.ts
    [tsl] ERROR in /home/me/project/src/ts/index.ts(9,28)
          TS2306: File '/home/me/project/src/assets/i18n/index.js' is not a module.
error Command failed with exit code 2.
```

I tried to use a `.ts` file as index for the i18n folder but it's the same. I'm doing something wrong?

Thanks!

PD: Maybe related to #14

**Comment by rosskevin** [comment]
I have both and `index.ts` and `index.js` for various reasons.  You must have a dummy export for it to be seen as a module.  Add both of those files with this content and you should be good:

```ts
export default {}
```

**Comment by wapcrazut** [comment]
Thank you for the response, I've tried that but it keeps throwing the same error on the `index.ts` file. I suppose that this has something to do with my setup or configuration.

**Comment by peitschie** [comment]
If it's of any help, I have an `index.d.ts` and an `index.js` instead. The `index.d.ts` contains the `export default {}` line as @rosskevin described.

**Comment by matsgm** [comment]
It also works having just an ```index.js``` with ```export default {};``` in a typescript project.

**Comment by toonjanssens** [comment]
I had the same issue and solved it by placing the i18next-loader rule in the webpack config before the ts-loader rule and I only used the index.ts with the empty object export.

```js
var config = {
  entry: './src/server.ts',
  mode: NODE_ENV,
  module: {
    rules: [
      {
        test: /locales/,
        loader: '@alienfast/i18next-loader',
      },
      {
        test: /\.ts$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
...
`
