### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by TannerS** [alienfast/i18next-loader#23]
https://github.com/advisories/GHSA-76p3-8jx3-jpfq

Any plans fixed for this?

**Comment by rosskevin** [comment]
PR it and we'll merge it

**Comment by rosskevin** [comment]
Feel free to `ncu -u` all dependencies...

**Comment by TannerS** [comment]
hey thanks @rosskevin  how do i test the new dep updates doesnt break anything?

**Comment by TannerS** [comment]
Any idea how to overcome this?

![image](https://user-images.githubusercontent.com/8866319/200355765-45877f42-45fa-45ab-83a4-2a38041a6a05.png)

@rosskevin

**Comment by rosskevin** [comment]
I'll look.  I transitioned the vite plugin to `intuit/auto`.  Hang on

**Comment by rosskevin** [comment]
@TannerS  I'll get this dependency update done.  I will also migrate it to github actions and intuit/auto for releases.

**Comment by TannerS** [comment]
thanks man

**Comment by rosskevin** [comment]
@TannerS do you mind trying the canary version and letting me know if it is good to go? https://github.com/alienfast/i18next-loader/pull/24

**Comment by TannerS** [comment]
ya sure @rosskevin

**Comment by TannerS** [comment]
Not sure if I have to wait for anything but im getting this 

```
LOG from webpack.FileSystemInfo
<w> Managed item /Users/tanners/projects/test/node_modules/@alienfast/i18next-loader isn't a directory or doesn't contain a package.json (see snapshot.managedPaths option)
+ 12 hidden lines

ERROR in ./src/client/i18n.js 4:0-38
Module not found: Error: Can't resolve '@alienfast/i18next-loader' in '/Users/tanners/projects/test'
resolve '@alienfast/i18next-loader' in '/Users/tanners/projects/test'
  Parsed request is a module
  using description file: /Users/tanners/projects/test/package.json (relative path: .)
    resolve as module
      looking for modules in /Users/tanners/projects/test/node_modules
        single file module
          using description file: /Users/tanners/projects/test/package.json (relative path: ./node_modules/@alienfast/i18next-loader)
            no extension
              /Users/tanners/projects/test/node_modules/@alienfast/i18next-loader doesn't exist
            .js
              /Users/tanners/projects/test/node_modules/@alienfast/i18next-loader.js doesn't exist
        /Users/tanners/projects/test/node_modules/@alienfast/i18next-loader doesn't exist
      /Users/tannersummers/Projects/node_modules doesn't exist or is not a directory
      /Users/tannersummers/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./src/client/App.js 4:0-16

webpack 5.74.0 compiled with 1 error in 9964 ms
```
![image](https://user-images.githubusercontent.com/8866319/200376794-48e173be-f76d-468c-b7a1-f3a8516921db.png)
![image](https://user-images.githubusercontent.com/8866319/200376834-a45e709a-fa24-461c-8cd0-81fbc067202c.png)


or if im installing it the incorrect way please let me know the proper way 

@rosskevin

**Comment by rosskevin** [comment]
You should be able to change your version to `"2.0.1--canary.24.74b2ccb.0"`, and it should load the canary build from gh package repo.  If not, tell me the yarn or npm error.

**Comment by TannerS** [comment]
ah ok ya that was my typo, trying now

**Comment by TannerS** [comment]
@rosskevin  ok with 

![image](https://user-images.githubusercontent.com/8866319/200377534-af5a8bb1-ce80-4e1a-bff2-b23ba9a84acf.png)


I get 

```
➜  feedback git:(master) ✗ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @alienfast/i18next-loader@2.0.1--canary.24.74b2ccb.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanners/.npm/_logs/2022-11-07T17_37_33_551Z-debug-0.log
➜  feedback git:(master) ✗
```

@rosskevin

**Comment by rosskevin** [comment]
FYI - it appears that intuit/auto publishes these PR canaries to the gh package repo, and this package is normally published on npmjs.com.  Not ...

Yeah....

Let me look that up.

**Comment by rosskevin** [comment]
Finally, try `2.0.1--canary.24.582e5cf.0`, it's on npm now.

**Comment by TannerS** [comment]
```
➜  feedback git:(master) ✗ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @alienfast/i18next-loader@2.0.1--canary.24.582e5cf.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tannersummers/.npm/_logs/2022-11-07T18_01_05_669Z-debug-0.log
➜  feedback git:(master) ✗
```

@rosskevin

**Comment by TannerS** [comment]
let me check something on our side

**Comment by TannerS** [comment]
So our company repo is not able to find it to test, but installing this package on my private laptops in a random repo worked fine. although i dont have a setup to test if it works the same until we see this version in the company repo

**Comment by TannerS** [comment]
we may not be able to allow canary versions

**Comment by rosskevin** [comment]
Ok, I going to go ahead and release.  Please alert me if things go wrong!

**Comment by rosskevin** [comment]
2.0.1 released

**Comment by TannerS** [comment]
thanks man!
