### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by CGAsierPaz** [alienfast/i18next-loader#25]
Hello.

This error is throwing when I tried this loader. It's because in the 22th line of the index.js it is calling a "getOptions" function that doesn't exists I guess.

**Comment by rosskevin** [comment]
Sorry for my lateness in response.  I believe the switch from loader-utils `getOptions` to Webpack 5 `this.getOptions` was made recently, so we are only compatible with 5.  Are you using Webpack 4?
