### ISSUE TITLE
documentation incorrent: key translation

### ISSUE THREAD

**Issue by AlexandreKilian** [alienfast/i18next-loader#5]
using this loaded, I found myself struggling to get it to work. In the end, I found out why:

if the file was locales/de/main.yaml, and the file would look like this:
```yaml
main:
  test: Das ist ein Test!
```
, the resulting resource would look like this:

```json
{ "de": {"main": { "test" : "Das ist ein Test!"}}}
```

to work, it would have to look like this:

```json
{ "de": {"translation": {"main": { "test" : "Das ist ein Test!"}}}}
```

as the defined structure needs a "translation" key:

https://www.i18next.com/getting-started.html

**Comment by rosskevin** [comment]
I'm sure you must be having some other problem. We use it every day, as-is with the structure defined in our readme. The correct structure is asserted by our unit tests.

In the getting started readme, `translation` is a context, an example would be a react component name, under which you can group keys.

So your original statement about the source and result is correct.

**Comment by AlexandreKilian** [comment]
yeah, turns out somehow "translation" was defined as the default namespace… I was able to reconfigure it, now it works, thx
